export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import 'bootstrap/dist/css/bootstrap.min.css';
import Nav from './nav/page';
import HeadComponent from './head-component/page';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeadComponent></HeadComponent>
        <Nav></Nav>
        {children}
      </body>
    </html>
  )
}
