export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import 'bootstrap/dist/css/bootstrap.min.css';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
